when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:
        faker:
            locale: fr_FR
        persistence:
            # Flush only once per call of `PersistentObjectFactory::create()`
            flush_once: true
        orm:
            reset:
                mode: migrate

when@test: *dev
